name: CI/CD pipeline

on:
  push:
    branches: ["main","CI_CD_Practice"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: ls
        run: ls
      - name: Run build with Gradle Wrapper
        run: ./gradlew build