name: CI/CD pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
        - name: Build with Gradle
          uses: gradle/gradle-build-action@v2.3.3
          with:
            arguments: build